/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MusicRouteImport } from './routes/music'
import { Route as PoetryRouteImport } from './routes/poetry'
import { Route as PressRouteImport } from './routes/press'
import { Route as ConcertsIndexRouteImport } from './routes/concerts.index'
import { Route as ConcertsSlugRouteImport } from './routes/concerts.$slug'
import { Route as MusicIndexRouteImport } from './routes/music.index'
import { Route as MusicConcertsRouteImport } from './routes/music.concerts'
import { Route as MusicImprovisationsRouteImport } from './routes/music.improvisations'
import { Route as MusicTranscriptionsIndexRouteImport } from './routes/music.transcriptions.index'
import { Route as MusicWorksSlugRouteImport } from './routes/music.works.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const PoetryRoute = PoetryRouteImport.update({
  id: '/poetry',
  path: '/poetry',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcertsIndexRoute = ConcertsIndexRouteImport.update({
  id: '/concerts/',
  path: '/concerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcertsSlugRoute = ConcertsSlugRouteImport.update({
  id: '/concerts/$slug',
  path: '/concerts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicIndexRoute = MusicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MusicRoute,
} as any)
const MusicConcertsRoute = MusicConcertsRouteImport.update({
  id: '/concerts',
  path: '/concerts',
  getParentRoute: () => MusicRoute,
} as any)
const MusicImprovisationsRoute = MusicImprovisationsRouteImport.update({
  id: '/improvisations',
  path: '/improvisations',
  getParentRoute: () => MusicRoute,
} as any)
const MusicTranscriptionsIndexRoute =
  MusicTranscriptionsIndexRouteImport.update({
    id: '/transcriptions/',
    path: '/transcriptions/',
    getParentRoute: () => MusicRoute,
  } as any)
const MusicWorksSlugRoute = MusicWorksSlugRouteImport.update({
  id: '/works/$slug',
  path: '/works/$slug',
  getParentRoute: () => MusicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/gallery': typeof GalleryRoute
  '/music': typeof MusicRouteWithChildren
  '/poetry': typeof PoetryRoute
  '/press': typeof PressRoute
  '/concerts/$slug': typeof ConcertsSlugRoute
  '/music/concerts': typeof MusicConcertsRoute
  '/music/improvisations': typeof MusicImprovisationsRoute
  '/concerts/': typeof ConcertsIndexRoute
  '/music/': typeof MusicIndexRoute
  '/music/works/$slug': typeof MusicWorksSlugRoute
  '/music/transcriptions/': typeof MusicTranscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/gallery': typeof GalleryRoute
  '/poetry': typeof PoetryRoute
  '/press': typeof PressRoute
  '/concerts/$slug': typeof ConcertsSlugRoute
  '/music/concerts': typeof MusicConcertsRoute
  '/music/improvisations': typeof MusicImprovisationsRoute
  '/concerts': typeof ConcertsIndexRoute
  '/music': typeof MusicIndexRoute
  '/music/works/$slug': typeof MusicWorksSlugRoute
  '/music/transcriptions': typeof MusicTranscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/gallery': typeof GalleryRoute
  '/music': typeof MusicRouteWithChildren
  '/poetry': typeof PoetryRoute
  '/press': typeof PressRoute
  '/concerts/$slug': typeof ConcertsSlugRoute
  '/music/concerts': typeof MusicConcertsRoute
  '/music/improvisations': typeof MusicImprovisationsRoute
  '/concerts/': typeof ConcertsIndexRoute
  '/music/': typeof MusicIndexRoute
  '/music/works/$slug': typeof MusicWorksSlugRoute
  '/music/transcriptions/': typeof MusicTranscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contacts'
    | '/gallery'
    | '/music'
    | '/poetry'
    | '/press'
    | '/concerts/$slug'
    | '/music/concerts'
    | '/music/improvisations'
    | '/concerts/'
    | '/music/'
    | '/music/works/$slug'
    | '/music/transcriptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contacts'
    | '/gallery'
    | '/poetry'
    | '/press'
    | '/concerts/$slug'
    | '/music/concerts'
    | '/music/improvisations'
    | '/concerts'
    | '/music'
    | '/music/works/$slug'
    | '/music/transcriptions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contacts'
    | '/gallery'
    | '/music'
    | '/poetry'
    | '/press'
    | '/concerts/$slug'
    | '/music/concerts'
    | '/music/improvisations'
    | '/concerts/'
    | '/music/'
    | '/music/works/$slug'
    | '/music/transcriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactsRoute: typeof ContactsRoute
  GalleryRoute: typeof GalleryRoute
  MusicRoute: typeof MusicRouteWithChildren
  PoetryRoute: typeof PoetryRoute
  PressRoute: typeof PressRoute
  ConcertsSlugRoute: typeof ConcertsSlugRoute
  ConcertsIndexRoute: typeof ConcertsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poetry': {
      id: '/poetry'
      path: '/poetry'
      fullPath: '/poetry'
      preLoaderRoute: typeof PoetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerts/': {
      id: '/concerts/'
      path: '/concerts'
      fullPath: '/concerts/'
      preLoaderRoute: typeof ConcertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerts/$slug': {
      id: '/concerts/$slug'
      path: '/concerts/$slug'
      fullPath: '/concerts/$slug'
      preLoaderRoute: typeof ConcertsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/': {
      id: '/music/'
      path: '/'
      fullPath: '/music/'
      preLoaderRoute: typeof MusicIndexRouteImport
      parentRoute: typeof MusicRoute
    }
    '/music/concerts': {
      id: '/music/concerts'
      path: '/concerts'
      fullPath: '/music/concerts'
      preLoaderRoute: typeof MusicConcertsRouteImport
      parentRoute: typeof MusicRoute
    }
    '/music/improvisations': {
      id: '/music/improvisations'
      path: '/improvisations'
      fullPath: '/music/improvisations'
      preLoaderRoute: typeof MusicImprovisationsRouteImport
      parentRoute: typeof MusicRoute
    }
    '/music/transcriptions/': {
      id: '/music/transcriptions/'
      path: '/transcriptions'
      fullPath: '/music/transcriptions/'
      preLoaderRoute: typeof MusicTranscriptionsIndexRouteImport
      parentRoute: typeof MusicRoute
    }
    '/music/works/$slug': {
      id: '/music/works/$slug'
      path: '/works/$slug'
      fullPath: '/music/works/$slug'
      preLoaderRoute: typeof MusicWorksSlugRouteImport
      parentRoute: typeof MusicRoute
    }
  }
}

interface MusicRouteChildren {
  MusicConcertsRoute: typeof MusicConcertsRoute
  MusicImprovisationsRoute: typeof MusicImprovisationsRoute
  MusicIndexRoute: typeof MusicIndexRoute
  MusicWorksSlugRoute: typeof MusicWorksSlugRoute
  MusicTranscriptionsIndexRoute: typeof MusicTranscriptionsIndexRoute
}

const MusicRouteChildren: MusicRouteChildren = {
  MusicConcertsRoute: MusicConcertsRoute,
  MusicImprovisationsRoute: MusicImprovisationsRoute,
  MusicIndexRoute: MusicIndexRoute,
  MusicWorksSlugRoute: MusicWorksSlugRoute,
  MusicTranscriptionsIndexRoute: MusicTranscriptionsIndexRoute,
}

const MusicRouteWithChildren = MusicRoute._addFileChildren(MusicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactsRoute: ContactsRoute,
  GalleryRoute: GalleryRoute,
  MusicRoute: MusicRouteWithChildren,
  PoetryRoute: PoetryRoute,
  PressRoute: PressRoute,
  ConcertsSlugRoute: ConcertsSlugRoute,
  ConcertsIndexRoute: ConcertsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
